// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetOs() {
  return window['go']['os_internal']['UIOsHelper']['GetOs']();
}
