// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AskForDirPath():Promise<string>;

export function OpenFileFolder(arg1:string):Promise<void>;
