// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDirPath() {
  return window['go']['fs']['UIFsHelper']['GetDirPath']();
}

export function SetContext(arg1) {
  return window['go']['fs']['UIFsHelper']['SetContext'](arg1);
}
