// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AskForDirPath() {
  return window['go']['fs']['UIFsHelper']['AskForDirPath']();
}

export function OpenFileFolder(arg1) {
  return window['go']['fs']['UIFsHelper']['OpenFileFolder'](arg1);
}

export function SetContext(arg1) {
  return window['go']['fs']['UIFsHelper']['SetContext'](arg1);
}
