// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {project} from '../models';
import {config} from '../models';

export function AddCommand(arg1:project.Command):Promise<void>;

export function CloseProject():Promise<void>;

export function CreateProject(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteProject(arg1:string):Promise<void>;

export function EditCommand(arg1:project.Command):Promise<void>;

export function EditProject(arg1:project.Project):Promise<void>;

export function ExportProject(arg1:string):Promise<void>;

export function GetAvailableProjects():Promise<Array<project.Project>>;

export function GetCommandGroups():Promise<Array<project.CommandGroup>>;

export function GetCommands():Promise<Record<string, project.Command>>;

export function GetCurrentProject():Promise<project.Project>;

export function GetProjectToImport():Promise<project.Project>;

export function GetUserConfig():Promise<config.UserConfig>;

export function ImportProject(arg1:project.Project):Promise<void>;

export function OpenProject(arg1:string):Promise<project.Project>;

export function RemoveCommand(arg1:string):Promise<void>;

export function RunCommand(arg1:string):Promise<Record<string, project.Command>>;

export function SaveCommandGroups(arg1:Array<project.CommandGroup>):Promise<void>;

export function SaveUserConfig(arg1:config.UserConfig):Promise<void>;

export function StopCommand(arg1:string):Promise<void>;
