// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportProject(arg1) {
  return window['go']['app']['App']['ExportProject'](arg1);
}

export function GetCurrentRelease() {
  return window['go']['app']['App']['GetCurrentRelease']();
}

export function GetProjectToImport() {
  return window['go']['app']['App']['GetProjectToImport']();
}

export function ImportProject(arg1, arg2, arg3) {
  return window['go']['app']['App']['ImportProject'](arg1, arg2, arg3);
}

export function IsThereANewRelease() {
  return window['go']['app']['App']['IsThereANewRelease']();
}

export function LoadDependencies(arg1) {
  return window['go']['app']['App']['LoadDependencies'](arg1);
}

export function RegisterHandlers() {
  return window['go']['app']['App']['RegisterHandlers']();
}

export function Startup(arg1) {
  return window['go']['app']['App']['Startup'](arg1);
}
