// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCommand(arg1) {
  return window['go']['app']['App']['AddCommand'](arg1);
}

export function EditCommand(arg1) {
  return window['go']['app']['App']['EditCommand'](arg1);
}

export function GetCommandGroups() {
  return window['go']['app']['App']['GetCommandGroups']();
}

export function GetCommands() {
  return window['go']['app']['App']['GetCommands']();
}

export function GetUserConfig() {
  return window['go']['app']['App']['GetUserConfig']();
}

export function RemoveCommand(arg1) {
  return window['go']['app']['App']['RemoveCommand'](arg1);
}

export function RunCommand(arg1) {
  return window['go']['app']['App']['RunCommand'](arg1);
}

export function SaveCommandGroups(arg1) {
  return window['go']['app']['App']['SaveCommandGroups'](arg1);
}

export function SaveUserConfig(arg1) {
  return window['go']['app']['App']['SaveUserConfig'](arg1);
}

export function StopCommand(arg1) {
  return window['go']['app']['App']['StopCommand'](arg1);
}
