// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {app} from '../models';
import {context} from '../models';

export function AddCommand(arg1:domain.Command):Promise<void>;

export function DeleteCommandGroup(arg1:string):Promise<void>;

export function DuplicateCommand(arg1:string,arg2:string):Promise<void>;

export function EditCommand(arg1:domain.Command):Promise<void>;

export function ExportProject(arg1:string):Promise<void>;

export function GetCommands():Promise<Array<domain.Command>>;

export function GetCurrentRelease():Promise<string>;

export function GetProjectToImport():Promise<app.ProjectExportJSONv1>;

export function ImportProject(arg1:app.ProjectExportJSONv1,arg2:string,arg3:string):Promise<void>;

export function IsThereANewRelease():Promise<string>;

export function LoadDependencies(arg1:app.Dependencies):Promise<void>;

export function RegisterHandlers():Promise<void>;

export function RemoveCommand(arg1:string):Promise<void>;

export function RemoveCommandFromCommandGroup(arg1:string,arg2:string):Promise<void>;

export function ReorderCommandGroups(arg1:Array<string>):Promise<void>;

export function ReorderCommands(arg1:Array<string>):Promise<void>;

export function RunCommand(arg1:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function StopCommand(arg1:string):Promise<void>;
