coverage:
  status:
    project:
      default:
        target: 80%
    patch:
      default:
        target: 70%

ignore:
  - "internal/apptest"
  - "internal/testdb"
  - "migrations/*.go"
  - "cmd/gomander/controllers.go"
  - "cmd/gomander/main.go"
  - "internal/app/app.go"
  - "**/*facade.go"
  - "**/*_testbuilder.go"
  - "**/*_mock.go"
