// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetComputedPath(arg1, arg2) {
  return window['go']['uihelpers']['PathHelper']['GetComputedPath'](arg1, arg2);
}
