// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadLatestRelease(arg1) {
  return window['go']['releases']['ReleaseHelper']['DownloadLatestRelease'](arg1);
}

export function GetCurrentRelease() {
  return window['go']['releases']['ReleaseHelper']['GetCurrentRelease']();
}

export function InstallLatestReleaseAndQuit(arg1) {
  return window['go']['releases']['ReleaseHelper']['InstallLatestReleaseAndQuit'](arg1);
}

export function IsThereANewRelease() {
  return window['go']['releases']['ReleaseHelper']['IsThereANewRelease']();
}

export function SetContext(arg1) {
  return window['go']['releases']['ReleaseHelper']['SetContext'](arg1);
}
