// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCurrentRelease():Promise<string>;

export function IsThereANewRelease():Promise<string>;
