// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function DownloadLatestRelease(arg1:string):Promise<string>;

export function GetCurrentRelease():Promise<string>;

export function InstallLatestReleaseAndQuit(arg1:string):Promise<void>;

export function IsThereANewRelease():Promise<string>;

export function SetContext(arg1:context.Context):Promise<void>;
