// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCurrentRelease() {
  return window['go']['releases']['ReleaseHelper']['GetCurrentRelease']();
}

export function IsThereANewRelease() {
  return window['go']['releases']['ReleaseHelper']['IsThereANewRelease']();
}
