// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadLatestRelease(arg1:string):Promise<string>;

export function GetCurrentRelease():Promise<string>;

export function InstallLatestReleaseAndQuit(arg1:string):Promise<void>;

export function IsThereANewRelease():Promise<string>;
