import type { BackendServices } from "@/contracts/ports.ts";
import {
	AskForDirPath,
	OpenFileFolder,
} from "../../../wailsjs/go/fs/UIFsHelper";
import {
	AddCommandController,
	CheckForNewReleaseController,
	CloseProjectController,
	CreateCommandGroupController,
	CreateProjectController,
	DeleteCommandGroupController,
	DeleteProjectController,
	DownloadReleaseController,
	DuplicateCommandController,
	EditCommandController,
	EditProjectController,
	ExportProjectController,
	GetAvailableProjectsController,
	GetCommandGroupsController,
	GetCommandsController,
	GetCurrentProjectController,
	GetCurrentReleaseController,
	GetProjectToImportController,
	GetProjectToImportFromPackageJsonController,
	GetSupportedLanguagesController,
	GetTranslationController,
	GetUserConfigController,
	ImportProjectController,
	InstallReleaseAndQuitController,
	OpenProjectController,
	RemoveCommandController,
	RemoveCommandFromCommandGroupController,
	ReorderCommandGroupsController,
	ReorderCommandsController,
	RunCommandController,
	RunCommandGroupController,
	SaveUserConfigController,
	StopCommandController,
	StopCommandGroupController,
	UpdateCommandGroupController,
} from "../../../wailsjs/go/main/WailsControllers";
import { GetOs } from "../../../wailsjs/go/os_internal/UIOsHelper";
import { GetComputedPath } from "../../../wailsjs/go/path/UiPathHelper";
import {
	BrowserOpenURL,
	ClipboardSetText,
	EventsOff,
	EventsOn,
} from "../../../wailsjs/runtime";

export const wailsBackend = {
	data: {
		addCommand: AddCommandController,
		duplicateCommand: DuplicateCommandController,
		editCommand: EditCommandController,
		reorderCommands: ReorderCommandsController,
		getAvailableProjects: GetAvailableProjectsController,
		editCommandGroup: UpdateCommandGroupController,
		createCommandGroup: CreateCommandGroupController,
		deleteCommandGroup: DeleteCommandGroupController,
		reorderCommandGroups: ReorderCommandGroupsController,
		removeCommandFromGroup: RemoveCommandFromCommandGroupController,
		runCommandGroup: RunCommandGroupController,
		stopCommandGroup: StopCommandGroupController,
		getCommandGroups: GetCommandGroupsController,
		getCommands: GetCommandsController,
		getCurrentProject: GetCurrentProjectController,
		getUserConfig: GetUserConfigController,
		removeCommand: RemoveCommandController,
		runCommand: RunCommandController,
		saveUserConfig: SaveUserConfigController,
		createProject: CreateProjectController,
		stopCommand: StopCommandController,
		openProject: OpenProjectController,
		closeProject: CloseProjectController,
		deleteProject: DeleteProjectController,
		exportProject: ExportProjectController,
		importProject: ImportProjectController,
		getProjectToImport: GetProjectToImportController,
		getProjectToImportFromPackageJson:
			GetProjectToImportFromPackageJsonController,
		editProject: EditProjectController,
		getCurrentRelease: GetCurrentReleaseController,
		checkForNewRelease: CheckForNewReleaseController,
		downloadRelease: DownloadReleaseController,
		installReleaseAndQuit: InstallReleaseAndQuitController,
	},
	helpers: {
		getComputedPath: GetComputedPath,
		getOs: GetOs,
		askForDirPath: AskForDirPath,
		openFileFolder: OpenFileFolder,
	},
	event: {
		eventsOn: EventsOn,
		eventsOff: EventsOff,
	},
	externalBrowser: {
		browserOpenURL: BrowserOpenURL,
	},
	clipboard: {
		setText: ClipboardSetText,
	},
	translations: {
		getTranslation: GetTranslationController,
		getSupportedLanguages: GetSupportedLanguagesController,
	},
} satisfies BackendServices;
