// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseProjectController() {
  return window['go']['main']['WailsControllers']['CloseProjectController']();
}

export function CreateCommandGroupController(arg1) {
  return window['go']['main']['WailsControllers']['CreateCommandGroupController'](arg1);
}

export function CreateProjectController(arg1) {
  return window['go']['main']['WailsControllers']['CreateProjectController'](arg1);
}

export function DeleteCommandGroupController(arg1) {
  return window['go']['main']['WailsControllers']['DeleteCommandGroupController'](arg1);
}

export function DeleteProjectController(arg1) {
  return window['go']['main']['WailsControllers']['DeleteProjectController'](arg1);
}

export function EditProjectController(arg1) {
  return window['go']['main']['WailsControllers']['EditProjectController'](arg1);
}

export function GetAvailableProjectsController() {
  return window['go']['main']['WailsControllers']['GetAvailableProjectsController']();
}

export function GetCommandGroupsController() {
  return window['go']['main']['WailsControllers']['GetCommandGroupsController']();
}

export function GetCurrentProjectController() {
  return window['go']['main']['WailsControllers']['GetCurrentProjectController']();
}

export function GetUserConfigController() {
  return window['go']['main']['WailsControllers']['GetUserConfigController']();
}

export function OpenProjectController(arg1) {
  return window['go']['main']['WailsControllers']['OpenProjectController'](arg1);
}

export function SaveUserConfigController(arg1) {
  return window['go']['main']['WailsControllers']['SaveUserConfigController'](arg1);
}

export function UpdateCommandGroupController(arg1) {
  return window['go']['main']['WailsControllers']['UpdateCommandGroupController'](arg1);
}
