// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function GetCurrentProjectController():Promise<domain.Project>;

export function GetUserConfigController():Promise<domain.Config>;

export function SaveUserConfigController(arg1:domain.Config):Promise<void>;
