// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function AddCommandController(arg1:domain.Command):Promise<void>;

export function CloseProjectController():Promise<void>;

export function CreateCommandGroupController(arg1:domain.CommandGroup):Promise<void>;

export function CreateProjectController(arg1:domain.Project):Promise<void>;

export function DeleteCommandGroupController(arg1:string):Promise<void>;

export function DeleteProjectController(arg1:string):Promise<void>;

export function DuplicateCommandController(arg1:string,arg2:string):Promise<void>;

export function EditCommandController(arg1:domain.Command):Promise<void>;

export function EditProjectController(arg1:domain.Project):Promise<void>;

export function ExportProjectController(arg1:string):Promise<string>;

export function GetAvailableProjectsController():Promise<Array<domain.Project>>;

export function GetCommandGroupsController():Promise<Array<domain.CommandGroup>>;

export function GetCommandsController():Promise<Array<domain.Command>>;

export function GetCurrentProjectController():Promise<domain.Project>;

export function GetProjectToImportController():Promise<domain.ProjectExportJSONv1>;

export function GetUserConfigController():Promise<domain.Config>;

export function ImportProjectController(arg1:domain.ProjectExportJSONv1,arg2:string,arg3:string):Promise<void>;

export function OpenProjectController(arg1:string):Promise<void>;

export function RemoveCommandController(arg1:string):Promise<void>;

export function RemoveCommandFromCommandGroupController(arg1:string,arg2:string):Promise<void>;

export function ReorderCommandGroupsController(arg1:Array<string>):Promise<void>;

export function ReorderCommandsController(arg1:Array<string>):Promise<void>;

export function RunCommandController(arg1:string):Promise<void>;

export function RunCommandGroupController(arg1:string):Promise<void>;

export function SaveUserConfigController(arg1:domain.Config):Promise<void>;

export function StopCommandController(arg1:string):Promise<void>;

export function StopCommandGroupController(arg1:string):Promise<void>;

export function UpdateCommandGroupController(arg1:domain.CommandGroup):Promise<void>;
