// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAvailableProjectsController() {
  return window['go']['main']['WailsControllers']['GetAvailableProjectsController']();
}

export function GetCurrentProjectController() {
  return window['go']['main']['WailsControllers']['GetCurrentProjectController']();
}

export function GetUserConfigController() {
  return window['go']['main']['WailsControllers']['GetUserConfigController']();
}

export function SaveUserConfigController(arg1) {
  return window['go']['main']['WailsControllers']['SaveUserConfigController'](arg1);
}
