// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddCommand(arg1:main.Command):Promise<void>;

export function EditCommand(arg1:main.Command):Promise<void>;

export function ExecCommand(arg1:string):Promise<void>;

export function GetCommands():Promise<Record<string, main.Command>>;

export function RemoveCommand(arg1:string):Promise<void>;

export function StopRunningCommand(arg1:string):Promise<void>;
