// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddCommand(arg1:main.Command):Promise<void>;

export function EditCommand(arg1:main.Command):Promise<void>;

export function GetCommandGroups():Promise<Array<main.CommandGroup>>;

export function GetCommands():Promise<Record<string, main.Command>>;

export function GetUserConfig():Promise<main.UserConfig>;

export function RemoveCommand(arg1:string):Promise<void>;

export function RunCommand(arg1:string):Promise<Record<string, main.Command>>;

export function SaveCommandGroups(arg1:Array<main.CommandGroup>):Promise<void>;

export function SaveUserConfig(arg1:main.UserConfig):Promise<void>;

export function StopCommand(arg1:string):Promise<void>;
