// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCommand(arg1) {
  return window['go']['main']['LogServer']['AddCommand'](arg1);
}

export function EditCommand(arg1) {
  return window['go']['main']['LogServer']['EditCommand'](arg1);
}

export function ExecCommand(arg1) {
  return window['go']['main']['LogServer']['ExecCommand'](arg1);
}

export function GetCommands() {
  return window['go']['main']['LogServer']['GetCommands']();
}

export function RemoveCommand(arg1) {
  return window['go']['main']['LogServer']['RemoveCommand'](arg1);
}
