name: Tests

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.0'

    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Download dependencies
      run: go mod download

    - name: Verify dependencies
      run: go mod verify

    - name: Create dummy frontend/dist directory
      run: |
        mkdir -p cmd/gomander/frontend/dist
        echo "dummy" > cmd/gomander/frontend/dist/.dummy

    - name: Run tests
      run: go test -v ./...
      # Uncomment the next line to enable coverage reporting
      # run: go test -v -coverprofile=coverage.out ./...

